import { NextRequest, NextResponse } from "next/server";
import * as XLSX from "xlsx";
import { supabaseAdmin } from "@/lib/supabase";

export const runtime = "nodejs";

// Column order mirrors the original "Monthly Fire Incident Monitoring"
// template (see lib/parseInvestigationReport.ts COL mapping) — flattened
// to a single header row rather than replicating the source's 3-row
// nested/merged header, which isn't necessary for the data to be
// immediately recognizable and usable by BFP officers.
function toExportRow(r: Record<string, unknown>) {
  return {
    Nr: r.source_row_nr,
    "Date of Fire": r.date_of_fire,
    "Time of Alarm": r.time_of_alarm_raw,
    Region: r.region,
    "Province / District": r.province_district,
    "City / Municipality": r.city_municipality,
    "Exact Location": r.exact_location,
    "Property Type (General)": r.property_general_category,
    "Property Type (Sub)": r.property_sub_category,
    "Name of Establishment": r.name_of_establishment,
    "Nr of Storeys": r.number_of_storeys,
    "Name of Owner": r.name_of_owner,
    "Name of Occupant": r.name_of_occupant,
    "Time Fire Started": r.time_fire_started_raw,
    "Fire Out": r.fire_out_raw,
    "Injured - Firefighter Male": r.injured_firefighter_male,
    "Injured - Firefighter Female": r.injured_firefighter_female,
    "Injured - Civilian Male": r.injured_civilian_male,
    "Injured - Civilian Female": r.injured_civilian_female,
    "Fatalities - Firefighter Male": r.fatalities_firefighter_male,
    "Fatalities - Firefighter Female": r.fatalities_firefighter_female,
    "Fatalities - Civilian Male": r.fatalities_civilian_male,
    "Fatalities - Civilian Female": r.fatalities_civilian_female,
    "Estimated Cost of Damage": r.estimated_cost_of_damage,
    "Nr of Affected Structures": r.number_of_affected_structures,
    Alarm: r.alarm_status,
    Cause: r.cause,
    "Classification of Case": r.classification_of_case,
    "Fire Arson Investigator": r.fire_arson_investigator,
    "Report - Spot": r.date_report_spot_raw,
    "Report - Progress": r.date_report_progress_raw,
    "Report - Final": r.date_report_final_raw,
    Remarks: r.remarks,
    // Extra columns not in the original template, but useful context for
    // an export generated by this system:
    "Match Status": r.match_status,
    "Linked Incident ID": r.incident_id,
    "Source File": r.source_file_name,
  };
}

export async function GET(req: NextRequest) {
  const sp = req.nextUrl.searchParams;
  const q = sp.get("q");
  const city = sp.get("city");
  const month = sp.get("month");
  const status = sp.get("status");

  let query = supabaseAdmin.from("investigation_records").select("*").order("date_of_fire", { ascending: false });

  if (city) query = query.eq("city_municipality", city);
  if (status === "matched" || status === "unmatched") query = query.eq("match_status", status);
  if (month) {
    const [year, m] = month.split("-").map(Number);
    const start = `${month}-01`;
    const nextMonth = m === 12 ? `${year + 1}-01-01` : `${year}-${String(m + 1).padStart(2, "0")}-01`;
    query = query.gte("date_of_fire", start).lt("date_of_fire", nextMonth);
  }
  if (q) {
    query = query.or(`exact_location.ilike.%${q}%,cause.ilike.%${q}%,fire_arson_investigator.ilike.%${q}%`);
  }

  const { data, error } = await query;

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
  if (!data || data.length === 0) {
    return NextResponse.json({ error: "No records match this filter — nothing to export." }, { status: 422 });
  }

  const rows = data.map(toExportRow);
  const ws = XLSX.utils.json_to_sheet(rows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Case Records");

  const buffer = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });

  const dateStamp = new Date().toISOString().slice(0, 10);
  return new NextResponse(buffer, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="BFP-NCR_Case_Records_${dateStamp}.xlsx"`,
    },
  });
}